python scripts/finetune_gemma.py \
  --model_name google/gemma-3-4b-it \
  --peft qlora \
  --fp16 true \
  --optim paged_adamw_8bit \
  --output_folder gemma3-4b-qlora-input_gold-output_numerical \
  --input_mode gold \
  --target_field numerical \
  --do_eval \
  --do_test \
  --eval_steps 200 \
  --per_device_train_batch_size 1 \
  --num_train_epochs 1 \
  --gradient_accumulation_steps 4 \
  --wandb_project finqa-gemma \
  --wandb_mode online \
  --wandb_run_name "Gemma3-4B QLoRA numerical | input=gold | 1ep" \
  --wandb_id "" \
  --wandb_resume never
